.\" Manpage for <autotoolscpplibtemplate>.
.\" Contact <owner-email> for comments or help.
.TH man 1 "May 2022" "1.1.0" "<autotoolscpplibtemplate> man page"
.SH NAME
<autotoolscpplibtemplate> \- Autotools Template for C++ Libraries
.SH SYNOPSIS
<autotoolscpplibtemplate>
.SH DESCRIPTION
<autotoolscpplibtemplate> is an Autotools Template for C++ Libraries.
.SH OPTIONS
<autotoolscpplibtemplate> does not take any arguments.
.SH BUGS
No known bugs.
.SH AUTHOR
<repo-owner> (<owner-email>)
