.\" Manpage for noisestreamer.
.\" Contact aldrigmej@gmail.com for comments or help.
.TH man 1 "May 2022" "1.1.0" "noisestreamer man page"
.SH NAME
noisestreamer \- Autotools Template for C++ Libraries
.SH SYNOPSIS
noisestreamer
.SH DESCRIPTION
noisestreamer is an Autotools Template for C++ Libraries.
.SH OPTIONS
noisestreamer does not take any arguments.
.SH BUGS
No known bugs.
.SH AUTHOR
Apostolos (aldrigmej@gmail.com)
